### ISSUE TITLE
Locally deleted messages cannot be recovered or replied to

### ISSUE THREAD

**Issue by alimpfard** [ferisystem/WhisperBot#3]
Repro steps:
- receive a message
- /inbox
- delete the message (locally)
- you can't get it back or reply to it

**Comment by ferisystem** [comment]
@alimpfard 
### Fixed
in https://github.com/ferisystem/WhisperBot/commit/79036664c80c2d6df9e8e5b16b5f83a666b77d09 & https://github.com/ferisystem/WhisperBot/commit/f893f129f1aa2cd3b8d7ad08c8bd093afd15bb04 Commits, solved.
